name: release
on:
  push:
    tags:
      - '*'
jobs:
  build:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: install
        run: python3 setup.py install
      - name: dist
        run: python3 setup.py sdist
      - name: distribute application
        uses: pypa/gh-action-pypi-publish@v1.1.0
        with:
          user: __token__
          password: ${{secrets.twine_password }}
          packages_dir: dist/
