---
name: release
"on":
  push:
    tags:
      - '*'
jobs:
  build:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: checkout
        run: git fetch --prune --unshallow
      - name: install
        run: python3 setup.py install
      - name: dist
        run: python3 setup.py sdist
      - name: distribute application
        uses: pypa/gh-action-pypi-publish@v1.1.0
        with:
          user: __token__
          password: ${{secrets.pypi_password}}
          packages_dir: dist/

  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Get tag
        id: repository
        run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/binxio/tfe-run-wait:${{ steps.repository.outputs.tag }}
